### PR TITLE
squash TODOs

### PR DESCRIPTION
**Pull request by oyiza**
✓ also rename `jobInfo` -> `jobModel`
✓ and there's no need to use `jobRepository` in `TableJobs.kt`

### CODE REVIEW

**Comment by pandyama** [comment]
Question, so the EditShift feature i am working on is obviously on a diff branch i created. So, with this Squash TODO PR, it will merge with develop branch but when I create a PR for EditShift, it wont have the Squash TODO changes, so how would this work?

**Comment by oyiza** [comment]
ideally, if the changes don't have any conflicts you'll be able to merge to develop without a hitch. however in this case, there'll probably be a minor conflict as i've renamed something in `ShiftsListModel.kt`. there are 2 options:

- leave this MR open for now until your changes are in and i'll deal with the conflicts; or
- after this MR is merged, you'll have to pull the new changes from develop to your local branch, resolve the conflicts there, then commit the changes and make your MR. if you're going with this option, you can test something: wait till you're done your EditShift stuff, then commit your changes, then do `git pull -r origin develop` to pull from develop with rebase and resolve conflicts then do `git push --force-with-lease` to push your changes

up to you, i dont mind either way lol i'll be out of town from tomorrow evening till sunday so i actually don't mind

**Comment by pandyama** [comment]
lets go with 2nd option. Merge this Squash TODO to develop and i'll follow your instructions and try it out when im done with EditShift

**Comment by oyiza** [comment]
sounds good.

**Pull request merged**
