### PR TITLE
Praise/odd 33 refactor helper use

### PR DESCRIPTION
**Pull request by oyiza**
moved getShiftType to jobRepository

### CODE REVIEW

**Comment by oyiza** [comment]
this might need some testing on your end.. making sure that adding shifts (same day and overnight) as well as editing shifts is still working as expected. i dont think anything should've changed but i might've made an error

i also tested on my end and nothing seemed broken

**Review by pandyama — COMMENTED** [review]
@oyiza ran through all the scenarios, overnight shifts are good, editing and deleting is good. One thing i noticed was when creating a job, the regex for job name field is not allowing a space... this might be my mistake for when i worked on this. Let me know if you want me to make that change to this PR, I can

**Comment by oyiza** [comment]
@pandyama ah i just tested that and you're right. 

i'd say create a separate linear ticket and branch for that fix instead. i'd like to keep the changes in this PR unique in case we ever need to revert

**Comment by pandyama** [comment]
@oyiza sure thing, i'll approve this now

**Review by pandyama — APPROVED** [review]

**Pull request merged**
