### PR TITLE
pass in shift details to edit shift dialog

### PR DESCRIPTION
**Pull request by oyiza**
✓ edit shift functionality now passes in shift details to the dialog
✓ rename c to calendar in homeadapter and childadapter

### CODE REVIEW

**Comment by oyiza** [comment]
@pandyama do we allow people work shifts of up to 48 hours? i know we can record shifts over 24 hours (by design) but what about over 48?

**Comment by pandyama** [comment]
> @pandyama do we allow people work shifts of up to 48 hours? i know we can record shifts over 24 hours (by design) but what about over 48?

I think we should only allow shifts to be less than 24 hours from when their shift started right? i mean no one will have a continuous shift of more than 12 hours realistically

**Comment by oyiza** [comment]
you're right. i'd have to test later on whether we can save a shift of more than 24 hours.. we can treat edit shifts with the same parameters as add shift

**Comment by oyiza** [comment]
okay so it looks like we don't stop users from saving a shift of up to 47 hours and 59 minutes. this is how it's always been so i guess it's up to a discussion on whether we want to keep it that way or change it but that's outside the scope of this PR then

image

**Comment by pandyama** [comment]
> okay so it looks like we don't stop users from saving a shift of up to 47 hours and 59 minutes. this is how it's always been so i guess it's up to a discussion on whether we want to keep it that way or change it but that's outside the scope of this PR then
> 
> image

yaa fair enough, we can decide that in a diff PR

**Comment by oyiza** [comment]
cool. i'd say this is ready for review then

**Review by pandyama — APPROVED** [review]
good to go

**Pull request merged**
