### PR TITLE
code refactoring

### PR DESCRIPTION
**Pull request by oyiza**
✓ removed description text from job card
✓ change access modifiers for variables in DatabaseHelper for better protection
✓ added some temporary logging to see what db was returning to the frontend
✓ reduced db calls to getAllJobs() in HomeFragment
✓ removed dummy list generation as it's no longer needed
✗ will have to move getAllJobs() method to JobRepository
✗ some refactoring work to do on the flow for user when job already exists in the db

### CODE REVIEW

**Comment by oyiza** [comment]
so the description above is for what i did so far. i'd really appreciate feedback / review / questions. feel free to checkout this branch and test it out locally as well to see if anything's off.! thanks

**Comment by pandyama** [comment]
I looked through the changes. I am good with the refactoring stuff. For getting all jobs in JobRepo, i'll have to do some googling to figure out how to get context and pass it to Databasehelper class. And, for changing the flow when user inputs a name and location that already exists, i think that's a fairly quick fix.

So, how do you want to do this? Do you want to merge this to develop and i'll create a new branch to work on those 2 changes and create a PR when i am ready

**Comment by oyiza** [comment]
sweet! ya i'll merge these to develop and you can create a branch for the work then.! thanks

**Comment by pandyama** [comment]
Ok cool, sounds good

**Pull request merged**
