### PR TITLE
praise/noJobsAddedYet

### PR DESCRIPTION
**Pull request by oyiza**
so for this one, my idea was that we'll need to decide whether to build the recyclerView or not before loading the first page. that's why i took out the testList object from the `generateDummyList()` method so we can decide what view to load when we call `onCreateView()`

let me know your thoughts

### CODE REVIEW

**Comment by pandyama** [comment]
yaa make sense. So, I saw this post [https://stackoverflow.com/questions/37772049/how-to-handle-empty-data-in-recycler-view](url) and it talks about how you can have a View made invisible and visible depending on a condition. I think this would help us avoid having to use a separate xml file. Wanna try it out? Im good with the current way you have setup too

**Comment by oyiza** [comment]
ah i see what you're saying. i tried out that method and it works just as well, except i keep getting this error message when i navigate away from home fragment and come back:
`E/RecyclerView: No adapter attached; skipping layout`
i think it's because with this other method, the recycler view layout is built regardless of whether we have data or not. just a guess, i can show you later if you want a demo

**Comment by pandyama** [comment]
oh true. If you're confident about that then let's go with the existing setup you have working. I'm cool with that.

**Comment by oyiza** [comment]
sounds good. after merging, i'll push the other implementation to github as well and park it in this branch!

**Comment by oyiza** [comment]
parked here: https://github.com/oyiza/OddHours/tree/parked/noJobsAddedYet_otherImplementation

**Comment by pandyama** [comment]
parked isnt a feature in git is it... you just created a branch under the name park right? so, that the implementation is still there to see

**Comment by oyiza** [comment]
oh no it isn't a feature. i just took advantage of the '/' naming convention. so any other implementation we want to keep track of, we can put it in `parked/...` branch

**Pull request merged**
