### PR TITLE
Feature/model creation

### PR DESCRIPTION
**Pull request by oyiza**
initial work on models, still much more to be done but i think it's a good start. anything else can be an improvement or refactor (hopefully not rewrite lol)

### CODE REVIEW

**Comment by pandyama** [comment]
So, I think the JobModel and JobInformationModel should be changed to mimic the database structure. JobModel can still be called JobModel just the properties are slightly updated. And, instead of JobInformationModel we should call it ShiftsModel. 
Again, this is just based on how I defined the database so far (it's on trello). Let me know what you think
Below would be the 2 models:
- JobModel (JobId, JobName, JobLocation)
- ShiftsModel (ShiftID, ShiftDate, JobID, StartTime, EndTime, HoursWorked)

**Comment by oyiza** [comment]
Right! i see what you're saying. i'll change the models to match the database structure.
what's your thoughts for the JobID and ShiftID? i thought we would generate IDs for the rows in the database? how do you propose we generate IDs for the models?

**Comment by pandyama** [comment]
So, if im not wrong, sqlite does autoincrement by default on Primary Keys in a table. I'll have to verify this, but if it's true then we don't have to generate any unique IDs, we can let SQLite generate those and we simply keep track of it in the JobModel and ShiftModel repository in kotlin. what do u think?

**Comment by oyiza** [comment]
ya i think you're right on the autoincrement stuff with sqlite. i guess i'm just wondering what we need the IDs for outside of the database. like if sqlite already generates the ids for us, we wont need to store it in the models (cause they're only useful during the app session) i think. did you have other uses for the modelID?

**Comment by pandyama** [comment]
i guess we would use to reference any given job and the overall shifts the user had added. This is because if the user for example has worked for the same company but in 2 diff location, we would reference it by using the jobid and not the jobname.

**Comment by oyiza** [comment]
i see. for some reason, i missed that you had JobID in ShiftsModel. okay that makes more sense then. that way, we wont need to have the jobName unique! i'll send in the changes in the next commit

**Comment by pandyama** [comment]
wait hold up. So, my shifts table does have jobid as a foreign key reference. So that every shift is tied to a given job.

**Comment by oyiza** [comment]
yup it does.. i didnt notice it initially :)

**Comment by oyiza** [comment]
hey take a look again at the models and let me know.. seems to me that the jobid should be generated by us and separate from the sqlite generated one. that way we can use it to lookup the shifts.. either way, i implemented as per your feedback for now and we can discuss and change as needed later!

**Pull request merged**
