### PR TITLE
praise/update to keep account active

### PR DESCRIPTION
**Pull request by oyiza**
- two separate commits. one's for removing the charts library and the other was some weird build things android studio did when i was fixing all the errors

### CODE REVIEW

**Review by pandyama — APPROVED** [review]
sweet, thanks, appreciate this

**Comment by pandyama** [comment]
@oyiza did you publish a new release too of the app?

**Comment by oyiza** [comment]
> @oyiza did you publish a new release too of the app?

i dont know how to do this... 😓

**Comment by pandyama** [comment]
> > @oyiza did you publish a new release too of the app?
> 
> i dont know how to do this... 😓

oh ok no problem.. can you find out from the google dev console what is our deadline for publishing an update?

**Pull request merged**
