### PR TITLE
Praise/squash TODOs

### PR DESCRIPTION
**Pull request by oyiza**
✓ revisit db methods and pass in models instead of jobName and jobLocation
✓ remove duplicate method in JobRepository
✓ renamed checkJobNameAndJobLocationExists to checkJobExists
✓ add shift creation method to jobRepository and moved calculateTotalHours to jobRepository
✓ change error message printing / logging just for uniformity
✓ TODOs down to 12 !!

### CODE REVIEW

**Comment by oyiza** [comment]
would be nice if we could automatically keep track of all the TODOs in code eh? VS Code has some extensions that kinda do that for you. anyway, feel free to comment in the MR and / or pull the branch and test in your local !!!

**Comment by pandyama** [comment]
question, why do we need buildJobModel and buildShiftsModel functions when we can just use their data class directly to build the object
so instead of val jobModel = jobRepository.buildJobModel(name, location) --> val jobModel = JobModel(name, location)

**Comment by pandyama** [comment]
> question, why do we need buildJobModel and buildShiftsModel functions when we can just use their data class directly to build the object
> so instead of val jobModel = jobRepository.buildJobModel(name, location) --> val jobModel = JobModel(name, location)

**Comment by pandyama** [comment]
> would be nice if we could automatically keep track of all the TODOs in code eh? VS Code has some extensions that kinda do that for you. anyway, feel free to comment in the MR and / or pull the branch and test in your local !!!

you mean from the code itself if we could parse it and keep track of it somewhere or whatever mechanism that exists for tracking TODOs?

**Comment by oyiza** [comment]
> question, why do we need buildJobModel and buildShiftsModel functions when we can just use their data class directly to build the object
> so instead of val jobModel = jobRepository.buildJobModel(name, location) --> val jobModel = JobModel(name, location)

good question: it's only for the fact that we technically want the repository classes handling all / most of the logic for us, that way we leave the view and viewModel classes to deal with just that - views!. at the moment, it doesn't make much of a difference but say we needed a lot more information and calculation to build a jobModel or shiftModel, it'd be better handled by the repository class.

**Comment by oyiza** [comment]
> > would be nice if we could automatically keep track of all the TODOs in code eh? VS Code has some extensions that kinda do that for you. anyway, feel free to comment in the MR and / or pull the branch and test in your local !!!
> 
> you mean from the code itself if we could parse it and keep track of it somewhere or whatever mechanism that exists for tracking TODOs?

yeah it's just wishful thinking.. i'd just like to keep track of TODOs and make sure the numbers are going down lol (OCD problems)

**Comment by pandyama** [comment]
> > question, why do we need buildJobModel and buildShiftsModel functions when we can just use their data class directly to build the object
> > so instead of val jobModel = jobRepository.buildJobModel(name, location) --> val jobModel = JobModel(name, location)
> 
> good question: it's only for the fact that we technically want the repository classes handling all / most of the logic for us, that way we leave the view and viewModel classes to deal with just that - views!. at the moment, it doesn't make much of a difference but say we needed a lot more information and calculation to build a jobModel or shiftModel, it'd be better handled by the repository class.

i feel like having these 2 build methods just to return the data class objects is redundant... because data class already provides us with that capability to just make an object by feeding it the values. In future, if we expand the jobmodel or shiftmodel, then we'd have to update the data classes & also update the build functions in jobRepository. The build methods in jobRepository are acting like setter & getter for an object, which is what data class already provides us with

**Comment by oyiza** [comment]
> > > question, why do we need buildJobModel and buildShiftsModel functions when we can just use their data class directly to build the object
> > > so instead of val jobModel = jobRepository.buildJobModel(name, location) --> val jobModel = JobModel(name, location)
> > 
> > 
> > good question: it's only for the fact that we technically want the repository classes handling all / most of the logic for us, that way we leave the view and viewModel classes to deal with just that - views!. at the moment, it doesn't make much of a difference but say we needed a lot more information and calculation to build a jobModel or shiftModel, it'd be better handled by the repository class.
> 
> i feel like having these 2 build methods just to return the data class objects is redundant... because data class already provides us with that capability to just make an object by feeding it the values. In future, if we expand the jobmodel or shiftmodel, then we'd have to update the data classes & also update the build functions in jobRepository. The build methods in jobRepository are acting like setter & getter for an object, which is what data class already provides us with

you're right. that makes a lot of sense... i'll update in the next commit.

**Comment by pandyama** [comment]
looks good bud!!

**Pull request merged**
